package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AddressType generated by hbm2java
 */
@Entity
@Table(name="address_type"
    ,schema="public"
)
public class AddressType  implements java.io.Serializable {


     private int id;
     private String addressTypeName;
     private Set<PersonAddress> personAddresses = new HashSet<PersonAddress>(0);

    public AddressType() {
    }

	
    public AddressType(int id, String addressTypeName) {
        this.id = id;
        this.addressTypeName = addressTypeName;
    }
    public AddressType(int id, String addressTypeName, Set<PersonAddress> personAddresses) {
       this.id = id;
       this.addressTypeName = addressTypeName;
       this.personAddresses = personAddresses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="address_type_name", nullable=false, length=40)
    public String getAddressTypeName() {
        return this.addressTypeName;
    }
    
    public void setAddressTypeName(String addressTypeName) {
        this.addressTypeName = addressTypeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="addressType")
    public Set<PersonAddress> getPersonAddresses() {
        return this.personAddresses;
    }
    
    public void setPersonAddresses(Set<PersonAddress> personAddresses) {
        this.personAddresses = personAddresses;
    }




}


