package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,schema="public"
)
public class Category  implements java.io.Serializable {


     private int id;
     private String categoryName;
     private String imageUrl;
     private Boolean isActive;
     private Set<CategoryClass> categoryClasses = new HashSet<CategoryClass>(0);
     private Set<ProductClassification> productClassifications = new HashSet<ProductClassification>(0);

    public Category() {
    }

	
    public Category(int id, String categoryName) {
        this.id = id;
        this.categoryName = categoryName;
    }
    public Category(int id, String categoryName, String imageUrl, Boolean isActive, Set<CategoryClass> categoryClasses, Set<ProductClassification> productClassifications) {
       this.id = id;
       this.categoryName = categoryName;
       this.imageUrl = imageUrl;
       this.isActive = isActive;
       this.categoryClasses = categoryClasses;
       this.productClassifications = productClassifications;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="category_name", nullable=false, length=60)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    
    @Column(name="image_url", length=100)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    
    @Column(name="is_active")
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<CategoryClass> getCategoryClasses() {
        return this.categoryClasses;
    }
    
    public void setCategoryClasses(Set<CategoryClass> categoryClasses) {
        this.categoryClasses = categoryClasses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<ProductClassification> getProductClassifications() {
        return this.productClassifications;
    }
    
    public void setProductClassifications(Set<ProductClassification> productClassifications) {
        this.productClassifications = productClassifications;
    }




}


