package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoryClass generated by hbm2java
 */
@Entity
@Table(name="category_class"
    ,schema="public"
)
public class CategoryClass  implements java.io.Serializable {


     private int id;
     private Category category;
     private String className;
     private String imageUrl;
     private Set<ProductClassification> productClassifications = new HashSet<ProductClassification>(0);

    public CategoryClass() {
    }

	
    public CategoryClass(int id, Category category, String className) {
        this.id = id;
        this.category = category;
        this.className = className;
    }
    public CategoryClass(int id, Category category, String className, String imageUrl, Set<ProductClassification> productClassifications) {
       this.id = id;
       this.category = category;
       this.className = className;
       this.imageUrl = imageUrl;
       this.productClassifications = productClassifications;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="class_name", nullable=false, length=60)
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }

    
    @Column(name="image_url", length=100)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoryClass")
    public Set<ProductClassification> getProductClassifications() {
        return this.productClassifications;
    }
    
    public void setProductClassifications(Set<ProductClassification> productClassifications) {
        this.productClassifications = productClassifications;
    }




}


