package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DocumentType generated by hbm2java
 */
@Entity
@Table(name="document_type"
    ,schema="public"
)
public class DocumentType  implements java.io.Serializable {


     private int id;
     private String documentName;
     private String description;
     private Set<Inventory> inventories = new HashSet<Inventory>(0);

    public DocumentType() {
    }

	
    public DocumentType(int id) {
        this.id = id;
    }
    public DocumentType(int id, String documentName, String description, Set<Inventory> inventories) {
       this.id = id;
       this.documentName = documentName;
       this.description = description;
       this.inventories = inventories;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="document_name", length=60)
    public String getDocumentName() {
        return this.documentName;
    }
    
    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="documentType")
    public Set<Inventory> getInventories() {
        return this.inventories;
    }
    
    public void setInventories(Set<Inventory> inventories) {
        this.inventories = inventories;
    }




}


