package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inventory generated by hbm2java
 */
@Entity
@Table(name="inventory"
    ,schema="public"
)
public class Inventory  implements java.io.Serializable {


     private int id;
     private DocumentType documentType;
     private Product product;
     private Store store;
     private User user;
     private int documentNumber;
     private BigDecimal amountIn;
     private BigDecimal amountOut;
     private BigDecimal balance;
     private Date registrationDate;

    public Inventory() {
    }

	
    public Inventory(int id, DocumentType documentType, Product product, Store store, User user, int documentNumber) {
        this.id = id;
        this.documentType = documentType;
        this.product = product;
        this.store = store;
        this.user = user;
        this.documentNumber = documentNumber;
    }
    public Inventory(int id, DocumentType documentType, Product product, Store store, User user, int documentNumber, BigDecimal amountIn, BigDecimal amountOut, BigDecimal balance, Date registrationDate) {
       this.id = id;
       this.documentType = documentType;
       this.product = product;
       this.store = store;
       this.user = user;
       this.documentNumber = documentNumber;
       this.amountIn = amountIn;
       this.amountOut = amountOut;
       this.balance = balance;
       this.registrationDate = registrationDate;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="document_type_id", nullable=false)
    public DocumentType getDocumentType() {
        return this.documentType;
    }
    
    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="store_id", nullable=false)
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="document_number", nullable=false)
    public int getDocumentNumber() {
        return this.documentNumber;
    }
    
    public void setDocumentNumber(int documentNumber) {
        this.documentNumber = documentNumber;
    }

    
    @Column(name="amount_in", scale=4)
    public BigDecimal getAmountIn() {
        return this.amountIn;
    }
    
    public void setAmountIn(BigDecimal amountIn) {
        this.amountIn = amountIn;
    }

    
    @Column(name="amount_out", scale=4)
    public BigDecimal getAmountOut() {
        return this.amountOut;
    }
    
    public void setAmountOut(BigDecimal amountOut) {
        this.amountOut = amountOut;
    }

    
    @Column(name="balance", scale=4)
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="registration_date", length=29)
    public Date getRegistrationDate() {
        return this.registrationDate;
    }
    
    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }




}


