package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvoiceHeader generated by hbm2java
 */
@Entity
@Table(name="invoice_header"
    ,schema="public"
)
public class InvoiceHeader  implements java.io.Serializable {


     private int id;
     private Customer customer;
     private DocumentStatus documentStatus;
     private OrderHeader orderHeader;
     private User user;
     private Date invoiceDate;
     private String notes;
     private String termsConditions;
     private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);

    public InvoiceHeader() {
    }

	
    public InvoiceHeader(int id, Customer customer, DocumentStatus documentStatus, OrderHeader orderHeader, User user) {
        this.id = id;
        this.customer = customer;
        this.documentStatus = documentStatus;
        this.orderHeader = orderHeader;
        this.user = user;
    }
    public InvoiceHeader(int id, Customer customer, DocumentStatus documentStatus, OrderHeader orderHeader, User user, Date invoiceDate, String notes, String termsConditions, Set<InvoiceDetail> invoiceDetails) {
       this.id = id;
       this.customer = customer;
       this.documentStatus = documentStatus;
       this.orderHeader = orderHeader;
       this.user = user;
       this.invoiceDate = invoiceDate;
       this.notes = notes;
       this.termsConditions = termsConditions;
       this.invoiceDetails = invoiceDetails;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status_id", nullable=false)
    public DocumentStatus getDocumentStatus() {
        return this.documentStatus;
    }
    
    public void setDocumentStatus(DocumentStatus documentStatus) {
        this.documentStatus = documentStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public OrderHeader getOrderHeader() {
        return this.orderHeader;
    }
    
    public void setOrderHeader(OrderHeader orderHeader) {
        this.orderHeader = orderHeader;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="invoice_date", length=29)
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    
    @Column(name="notes")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @Column(name="terms_conditions")
    public String getTermsConditions() {
        return this.termsConditions;
    }
    
    public void setTermsConditions(String termsConditions) {
        this.termsConditions = termsConditions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="invoiceHeader")
    public Set<InvoiceDetail> getInvoiceDetails() {
        return this.invoiceDetails;
    }
    
    public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }




}


