package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MainMenu generated by hbm2java
 */
@Entity
@Table(name="main_menu"
    ,schema="public"
)
public class MainMenu  implements java.io.Serializable {


     private int id;
     private MainMenu mainMenu;
     private String windowName;
     private String title;
     private String description;
     private Boolean isVisible;
     private Set<Permission> permissions = new HashSet<Permission>(0);
     private Set<MainMenu> mainMenus = new HashSet<MainMenu>(0);

    public MainMenu() {
    }

	
    public MainMenu(int id, String title) {
        this.id = id;
        this.title = title;
    }
    public MainMenu(int id, MainMenu mainMenu, String windowName, String title, String description, Boolean isVisible, Set<Permission> permissions, Set<MainMenu> mainMenus) {
       this.id = id;
       this.mainMenu = mainMenu;
       this.windowName = windowName;
       this.title = title;
       this.description = description;
       this.isVisible = isVisible;
       this.permissions = permissions;
       this.mainMenus = mainMenus;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent_id")
    public MainMenu getMainMenu() {
        return this.mainMenu;
    }
    
    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }

    
    @Column(name="window_name", length=100)
    public String getWindowName() {
        return this.windowName;
    }
    
    public void setWindowName(String windowName) {
        this.windowName = windowName;
    }

    
    @Column(name="title", nullable=false, length=40)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="is_visible")
    public Boolean getIsVisible() {
        return this.isVisible;
    }
    
    public void setIsVisible(Boolean isVisible) {
        this.isVisible = isVisible;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mainMenu")
    public Set<Permission> getPermissions() {
        return this.permissions;
    }
    
    public void setPermissions(Set<Permission> permissions) {
        this.permissions = permissions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="mainMenu")
    public Set<MainMenu> getMainMenus() {
        return this.mainMenus;
    }
    
    public void setMainMenus(Set<MainMenu> mainMenus) {
        this.mainMenus = mainMenus;
    }




}


