package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MeasureUnit generated by hbm2java
 */
@Entity
@Table(name="measure_unit"
    ,schema="public"
)
public class MeasureUnit  implements java.io.Serializable {


     private int id;
     private String measureUnitName;
     private String symbol;
     private Set<Product> products = new HashSet<Product>(0);

    public MeasureUnit() {
    }

	
    public MeasureUnit(int id, String measureUnitName, String symbol) {
        this.id = id;
        this.measureUnitName = measureUnitName;
        this.symbol = symbol;
    }
    public MeasureUnit(int id, String measureUnitName, String symbol, Set<Product> products) {
       this.id = id;
       this.measureUnitName = measureUnitName;
       this.symbol = symbol;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="measure_unit_name", nullable=false, length=30)
    public String getMeasureUnitName() {
        return this.measureUnitName;
    }
    
    public void setMeasureUnitName(String measureUnitName) {
        this.measureUnitName = measureUnitName;
    }

    
    @Column(name="symbol", nullable=false, length=10)
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="measureUnit")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


