package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name="order_detail"
    ,schema="public"
)
public class OrderDetail  implements java.io.Serializable {


     private int id;
     private OrderHeader orderHeader;
     private Product product;
     private BigDecimal quantity;
     private BigDecimal unitPrice;
     private Set<InvoiceDetail> invoiceDetails = new HashSet<InvoiceDetail>(0);

    public OrderDetail() {
    }

	
    public OrderDetail(int id, OrderHeader orderHeader, Product product, BigDecimal quantity, BigDecimal unitPrice) {
        this.id = id;
        this.orderHeader = orderHeader;
        this.product = product;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }
    public OrderDetail(int id, OrderHeader orderHeader, Product product, BigDecimal quantity, BigDecimal unitPrice, Set<InvoiceDetail> invoiceDetails) {
       this.id = id;
       this.orderHeader = orderHeader;
       this.product = product;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.invoiceDetails = invoiceDetails;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="order_id", nullable=false)
    public OrderHeader getOrderHeader() {
        return this.orderHeader;
    }
    
    public void setOrderHeader(OrderHeader orderHeader) {
        this.orderHeader = orderHeader;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity", nullable=false, scale=4)
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="unit_price", nullable=false, scale=4)
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="orderDetail")
    public Set<InvoiceDetail> getInvoiceDetails() {
        return this.invoiceDetails;
    }
    
    public void setInvoiceDetails(Set<InvoiceDetail> invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }




}


