package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name="permission"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"window_name", "action_name"}) 
)
public class Permission  implements java.io.Serializable {


     private int id;
     private MainMenu mainMenu;
     private String windowName;
     private String actionName;
     private String description;
     private Set<RolePermission> rolePermissions = new HashSet<RolePermission>(0);

    public Permission() {
    }

	
    public Permission(int id, MainMenu mainMenu) {
        this.id = id;
        this.mainMenu = mainMenu;
    }
    public Permission(int id, MainMenu mainMenu, String windowName, String actionName, String description, Set<RolePermission> rolePermissions) {
       this.id = id;
       this.mainMenu = mainMenu;
       this.windowName = windowName;
       this.actionName = actionName;
       this.description = description;
       this.rolePermissions = rolePermissions;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menu_id", nullable=false)
    public MainMenu getMainMenu() {
        return this.mainMenu;
    }
    
    public void setMainMenu(MainMenu mainMenu) {
        this.mainMenu = mainMenu;
    }

    
    @Column(name="window_name", length=100)
    public String getWindowName() {
        return this.windowName;
    }
    
    public void setWindowName(String windowName) {
        this.windowName = windowName;
    }

    
    @Column(name="action_name", length=60)
    public String getActionName() {
        return this.actionName;
    }
    
    public void setActionName(String actionName) {
        this.actionName = actionName;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="permission")
    public Set<RolePermission> getRolePermissions() {
        return this.rolePermissions;
    }
    
    public void setRolePermissions(Set<RolePermission> rolePermissions) {
        this.rolePermissions = rolePermissions;
    }




}


