package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PersonAddress generated by hbm2java
 */
@Entity
@Table(name="person_address"
    ,schema="public"
)
public class PersonAddress  implements java.io.Serializable {


     private int id;
     private AddressType addressType;
     private Person person;
     private String addressLine1;
     private String addressLine2;
     private String city;
     private String province;
     private String country;

    public PersonAddress() {
    }

	
    public PersonAddress(int id, AddressType addressType, Person person, String addressLine1, String city, String province, String country) {
        this.id = id;
        this.addressType = addressType;
        this.person = person;
        this.addressLine1 = addressLine1;
        this.city = city;
        this.province = province;
        this.country = country;
    }
    public PersonAddress(int id, AddressType addressType, Person person, String addressLine1, String addressLine2, String city, String province, String country) {
       this.id = id;
       this.addressType = addressType;
       this.person = person;
       this.addressLine1 = addressLine1;
       this.addressLine2 = addressLine2;
       this.city = city;
       this.province = province;
       this.country = country;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="address_type_id", nullable=false)
    public AddressType getAddressType() {
        return this.addressType;
    }
    
    public void setAddressType(AddressType addressType) {
        this.addressType = addressType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="person_id", nullable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

    
    @Column(name="address_line_1", nullable=false, length=100)
    public String getAddressLine1() {
        return this.addressLine1;
    }
    
    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    
    @Column(name="address_line_2", length=100)
    public String getAddressLine2() {
        return this.addressLine2;
    }
    
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    
    @Column(name="city", nullable=false, length=60)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="province", nullable=false, length=60)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

    
    @Column(name="country", nullable=false, length=60)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }




}


