package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PersonPhones generated by hbm2java
 */
@Entity
@Table(name="person_phones"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="phone_type_id") 
)
public class PersonPhones  implements java.io.Serializable {


     private int id;
     private Person person;
     private PhoneType phoneType;
     private String phoneNumber;

    public PersonPhones() {
    }

    public PersonPhones(int id, Person person, PhoneType phoneType, String phoneNumber) {
       this.id = id;
       this.person = person;
       this.phoneType = phoneType;
       this.phoneNumber = phoneNumber;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="person_id", nullable=false)
    public Person getPerson() {
        return this.person;
    }
    
    public void setPerson(Person person) {
        this.person = person;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="phone_type_id", unique=true, nullable=false)
    public PhoneType getPhoneType() {
        return this.phoneType;
    }
    
    public void setPhoneType(PhoneType phoneType) {
        this.phoneType = phoneType;
    }

    
    @Column(name="phone_number", nullable=false, length=60)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }




}


