package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonType generated by hbm2java
 */
@Entity
@Table(name="person_type"
    ,schema="public"
)
public class PersonType  implements java.io.Serializable {


     private int id;
     private String personTypeName;
     private Set<Person> persons = new HashSet<Person>(0);

    public PersonType() {
    }

	
    public PersonType(int id, String personTypeName) {
        this.id = id;
        this.personTypeName = personTypeName;
    }
    public PersonType(int id, String personTypeName, Set<Person> persons) {
       this.id = id;
       this.personTypeName = personTypeName;
       this.persons = persons;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="person_type_name", nullable=false, length=50)
    public String getPersonTypeName() {
        return this.personTypeName;
    }
    
    public void setPersonTypeName(String personTypeName) {
        this.personTypeName = personTypeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personType")
    public Set<Person> getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set<Person> persons) {
        this.persons = persons;
    }




}


