package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhoneType generated by hbm2java
 */
@Entity
@Table(name="phone_type"
    ,schema="public"
)
public class PhoneType  implements java.io.Serializable {


     private int id;
     private String phoneTypeName;
     private Set<PersonPhones> personPhoneses = new HashSet<PersonPhones>(0);

    public PhoneType() {
    }

	
    public PhoneType(int id, String phoneTypeName) {
        this.id = id;
        this.phoneTypeName = phoneTypeName;
    }
    public PhoneType(int id, String phoneTypeName, Set<PersonPhones> personPhoneses) {
       this.id = id;
       this.phoneTypeName = phoneTypeName;
       this.personPhoneses = personPhoneses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="phone_type_name", nullable=false, length=40)
    public String getPhoneTypeName() {
        return this.phoneTypeName;
    }
    
    public void setPhoneTypeName(String phoneTypeName) {
        this.phoneTypeName = phoneTypeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phoneType")
    public Set<PersonPhones> getPersonPhoneses() {
        return this.personPhoneses;
    }
    
    public void setPersonPhoneses(Set<PersonPhones> personPhoneses) {
        this.personPhoneses = personPhoneses;
    }




}


