package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PriceListType generated by hbm2java
 */
@Entity
@Table(name="price_list_type"
    ,schema="public"
)
public class PriceListType  implements java.io.Serializable {


     private int id;
     private String priceListTypeName;
     private Boolean isDefault;
     private Set<Customer> customers = new HashSet<Customer>(0);
     private Set<PriceListProduct> priceListProducts = new HashSet<PriceListProduct>(0);

    public PriceListType() {
    }

	
    public PriceListType(int id) {
        this.id = id;
    }
    public PriceListType(int id, String priceListTypeName, Boolean isDefault, Set<Customer> customers, Set<PriceListProduct> priceListProducts) {
       this.id = id;
       this.priceListTypeName = priceListTypeName;
       this.isDefault = isDefault;
       this.customers = customers;
       this.priceListProducts = priceListProducts;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="price_list_type_name", length=40)
    public String getPriceListTypeName() {
        return this.priceListTypeName;
    }
    
    public void setPriceListTypeName(String priceListTypeName) {
        this.priceListTypeName = priceListTypeName;
    }

    
    @Column(name="is_default")
    public Boolean getIsDefault() {
        return this.isDefault;
    }
    
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="priceListType")
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="priceListType")
    public Set<PriceListProduct> getPriceListProducts() {
        return this.priceListProducts;
    }
    
    public void setPriceListProducts(Set<PriceListProduct> priceListProducts) {
        this.priceListProducts = priceListProducts;
    }




}


