package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PriceListProduct generated by hbm2java
 */
@Entity
@Table(name="price_list_product"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"product_id", "price_list_type_id"}) 
)
public class PriceListProduct  implements java.io.Serializable {


     private int id;
     private PriceListType priceListType;
     private Product product;
     private BigDecimal sellPrice;
     private BigDecimal discountMax;

    public PriceListProduct() {
    }

	
    public PriceListProduct(int id, PriceListType priceListType, Product product, BigDecimal sellPrice) {
        this.id = id;
        this.priceListType = priceListType;
        this.product = product;
        this.sellPrice = sellPrice;
    }
    public PriceListProduct(int id, PriceListType priceListType, Product product, BigDecimal sellPrice, BigDecimal discountMax) {
       this.id = id;
       this.priceListType = priceListType;
       this.product = product;
       this.sellPrice = sellPrice;
       this.discountMax = discountMax;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="price_list_type_id", nullable=false)
    public PriceListType getPriceListType() {
        return this.priceListType;
    }
    
    public void setPriceListType(PriceListType priceListType) {
        this.priceListType = priceListType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="sell_price", nullable=false, scale=4)
    public BigDecimal getSellPrice() {
        return this.sellPrice;
    }
    
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    
    @Column(name="discount_max", scale=4)
    public BigDecimal getDiscountMax() {
        return this.discountMax;
    }
    
    public void setDiscountMax(BigDecimal discountMax) {
        this.discountMax = discountMax;
    }




}


