package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProductClassification generated by hbm2java
 */
@Entity
@Table(name="product_classification"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"product_id", "category_id", "class_id"}) 
)
public class ProductClassification  implements java.io.Serializable {


     private int id;
     private Category category;
     private CategoryClass categoryClass;
     private Product product;

    public ProductClassification() {
    }

    public ProductClassification(int id, Category category, CategoryClass categoryClass, Product product) {
       this.id = id;
       this.category = category;
       this.categoryClass = categoryClass;
       this.product = product;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="class_id", nullable=false)
    public CategoryClass getCategoryClass() {
        return this.categoryClass;
    }
    
    public void setCategoryClass(CategoryClass categoryClass) {
        this.categoryClass = categoryClass;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }




}


