package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductType generated by hbm2java
 */
@Entity
@Table(name="product_type"
    ,schema="public"
)
public class ProductType  implements java.io.Serializable {


     private int id;
     private String productTypeName;
     private Set<Product> products = new HashSet<Product>(0);

    public ProductType() {
    }

	
    public ProductType(int id, String productTypeName) {
        this.id = id;
        this.productTypeName = productTypeName;
    }
    public ProductType(int id, String productTypeName, Set<Product> products) {
       this.id = id;
       this.productTypeName = productTypeName;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="product_type_name", nullable=false, length=30)
    public String getProductTypeName() {
        return this.productTypeName;
    }
    
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="productType")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


