package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StockLevelProduct generated by hbm2java
 */
@Entity
@Table(name="stock_level_product"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"product_id", "store_id"}) 
)
public class StockLevelProduct  implements java.io.Serializable {


     private int id;
     private Product product;
     private Store store;
     private BigDecimal stockMax;
     private BigDecimal stockMin;

    public StockLevelProduct() {
    }

	
    public StockLevelProduct(int id, Product product, Store store) {
        this.id = id;
        this.product = product;
        this.store = store;
    }
    public StockLevelProduct(int id, Product product, Store store, BigDecimal stockMax, BigDecimal stockMin) {
       this.id = id;
       this.product = product;
       this.store = store;
       this.stockMax = stockMax;
       this.stockMin = stockMin;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="store_id", nullable=false)
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }

    
    @Column(name="stock_max", scale=4)
    public BigDecimal getStockMax() {
        return this.stockMax;
    }
    
    public void setStockMax(BigDecimal stockMax) {
        this.stockMax = stockMax;
    }

    
    @Column(name="stock_min", scale=4)
    public BigDecimal getStockMin() {
        return this.stockMin;
    }
    
    public void setStockMin(BigDecimal stockMin) {
        this.stockMin = stockMin;
    }




}


