package entities;
// Generated 19/05/2015 04:34:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaxGroup generated by hbm2java
 */
@Entity
@Table(name="tax_group"
    ,schema="public"
)
public class TaxGroup  implements java.io.Serializable {


     private int id;
     private TaxType taxType;
     private String taxGroupName;
     private Set<Product> products = new HashSet<Product>(0);

    public TaxGroup() {
    }

	
    public TaxGroup(int id, TaxType taxType, String taxGroupName) {
        this.id = id;
        this.taxType = taxType;
        this.taxGroupName = taxGroupName;
    }
    public TaxGroup(int id, TaxType taxType, String taxGroupName, Set<Product> products) {
       this.id = id;
       this.taxType = taxType;
       this.taxGroupName = taxGroupName;
       this.products = products;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tax_type_id", nullable=false)
    public TaxType getTaxType() {
        return this.taxType;
    }
    
    public void setTaxType(TaxType taxType) {
        this.taxType = taxType;
    }

    
    @Column(name="tax_group_name", nullable=false, length=30)
    public String getTaxGroupName() {
        return this.taxGroupName;
    }
    
    public void setTaxGroupName(String taxGroupName) {
        this.taxGroupName = taxGroupName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="taxGroup")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


